name: Package for Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # Build and Package Code
      - name: Build with Maven
        run: mvn clean package

      # Upload Build Artifacts
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: packaged-app
          path: target/*.jar
